import { useEffect, useMemo, useState } from 'react'
import type { PropsWithChildren } from 'react'
import { PreferencesContext } from './preferences-context'
import type {
  Language,
  PreferencesContextValue,
  Theme,
  TranslationKey,
} from './preferences-context'

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    'app.setup': 'AERA Setup',
    'app.missingSupabase': 'Supabase configuration is missing',
    'app.missingSupabaseBody':
      'The app cannot start because there is no .env file with the required environment variables.',
    'app.createEnv': 'Create a `.env` file in the project root with:',
    'app.restartVite': 'Then restart Vite with `npm run dev`.',
    'layout.brandTitle': 'Perfume operations with clarity',
    'layout.mobileTitle': 'Operations hub',
    'layout.signOut': 'Sign out',
    'layout.language': 'Language',
    'layout.theme': 'Theme',
    'layout.openMenu': 'Open menu',
    'layout.closeMenu': 'Close menu',
    'layout.themeLight': 'Light',
    'layout.themeDark': 'Dark',
    'layout.langEnglish': 'English',
    'layout.langSpanish': 'Spanish',
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.materials': 'Materials',
    'nav.sales': 'Sales',
    'nav.purchases': 'Purchases',
    'nav.inventory': 'Inventory',
    'auth.welcome': 'Welcome',
    'auth.loginTitle': 'Sign in to AERA',
    'auth.registerTitle': 'Create your account',
    'auth.subtitle':
      'Use Supabase email/password authentication to access your private workspace.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.submitWait': 'Please wait...',
    'auth.signIn': 'Sign in',
    'auth.createAccount': 'Create account',
    'auth.needAccount': 'Need an account? Register',
    'auth.haveAccount': 'Already have an account? Sign in',
    'auth.created': 'Account created. Check your email if confirmation is enabled.',
    'auth.failed': 'Authentication failed.',
    'auth.heroTitle': 'Accounting and inventory built for modern perfume brands.',
    'auth.heroDescription':
      'Track products, purchases, sales, stock, and profitability from one clean workspace.',
    'auth.cardSalesTitle': 'Sales control',
    'auth.cardSalesCopy': 'Multi-item sales with live totals',
    'auth.cardPurchasesTitle': 'Purchase flow',
    'auth.cardPurchasesCopy': 'Fast inventory intake and cost capture',
    'auth.cardProfitTitle': 'Profit visibility',
    'auth.cardProfitCopy': 'KPIs and margin insights in one dashboard',
    'pageHeader.eyebrow': 'Business overview',
    'dashboard.title': 'Dashboard',
    'dashboard.description':
      'Track your business performance with a premium overview of revenue, margin, and inventory.',
    'dashboard.totalSales': 'Total Sales',
    'dashboard.grossProfit': 'Gross Profit',
    'dashboard.materialsValue': 'Materials Value',
    'dashboard.profitMargin': 'Profit Margin',
    'dashboard.lowStock': 'Low Stock Alerts',
    'dashboard.revenueTrend': 'Revenue trend',
    'dashboard.revenueTrendDescription':
      'A simplified view of recent sales with a clean, axis-free chart.',
    'dashboard.loading': 'Loading analytics...',
    'dashboard.lowStockAlerts': 'Low stock materials',
    'dashboard.lowStockDescription': 'Materials that are close to running out based on a default threshold.',
    'dashboard.lowStockEmpty': 'No low stock alerts right now.',
    'dashboard.lowStockThreshold': 'Threshold',
    'materials.title': 'Materials',
    'materials.description':
      'Manage your real inventory of alcohol, essences, bottles, and every production input.',
    'materials.add': 'Add material',
    'materials.edit': 'Edit material',
    'materials.formDescription': 'Create and update raw materials used in production.',
    'materials.catalog': 'Materials inventory',
    'materials.catalogDescription': 'Current stock levels for every supply in your operation.',
    'materials.empty': 'No materials yet. Add your first supply to start producing.',
    'materials.name': 'Name',
    'materials.stock': 'Stock',
    'materials.unit': 'Unit',
    'materials.actions': 'Actions',
    'materials.editAction': 'Edit',
    'materials.deleteAction': 'Delete',
    'products.title': 'Products',
    'products.description':
      'Maintain your perfume catalog and define exactly which materials each product consumes.',
    'products.add': 'Add product',
    'products.edit': 'Edit product',
    'products.formDescription': 'Create products with price and bill of materials.',
    'products.catalog': 'Catalog',
    'products.catalogDescription': 'All products available in your account.',
    'products.empty': 'No products yet. Add your first perfume to get started.',
    'products.name': 'Name',
    'products.price': 'Price',
    'products.bom': 'Composition',
    'products.bomEmpty': 'No materials assigned',
    'products.actions': 'Actions',
    'products.editAction': 'Edit',
    'products.deleteAction': 'Delete',
    'productForm.name': 'Product name',
    'productForm.price': 'Sale price',
    'productForm.placeholder': 'Eau de Parfum',
    'productForm.composition': 'Bill of materials',
    'productForm.selectMaterial': 'Select a material',
    'productForm.quantityRequired': 'Quantity per unit',
    'productForm.addMaterial': 'Add material',
    'productForm.removeMaterial': 'Remove',
    'productForm.emptyBom': 'Add at least one material to define the composition.',
    'productForm.save': 'Saving...',
    'productForm.update': 'Update',
    'productForm.add': 'Add product',
    'productForm.cancel': 'Cancel',
    'materialForm.name': 'Material name',
    'materialForm.stock': 'Current stock',
    'materialForm.unit': 'Unit',
    'materialForm.placeholder': 'Alcohol',
    'materialForm.unitPlaceholder': 'ml, grams, units',
    'materialForm.save': 'Saving...',
    'materialForm.update': 'Update',
    'materialForm.add': 'Add material',
    'materialForm.cancel': 'Cancel',
    'sales.title': 'Sales',
    'sales.description':
      'Register sales and automatically consume the required raw materials from each product composition.',
    'sales.newSale': 'New sale',
    'sales.newSaleDescription':
      'Each sale validates material availability before it is confirmed.',
    'sales.history': 'Recent sales',
    'sales.historyDescription': 'A history of submitted transactions.',
    'sales.empty': 'No sales recorded yet.',
    'sales.date': 'Date',
    'sales.items': 'Items',
    'sales.total': 'Total',
    'sales.productFallback': 'Product',
    'sales.validationError': 'Insufficient materials',
    'sales.ready': 'Materials available',
    'saleForm.product': 'Product',
    'saleForm.selectProduct': 'Select a product',
    'saleForm.quantity': 'Quantity',
    'saleForm.price': 'Price',
    'saleForm.remove': 'Remove',
    'saleForm.addLine': 'Add another item',
    'saleForm.calculatedTotal': 'Calculated total',
    'saleForm.validationHint': 'AERA will validate the required materials before saving the sale.',
    'saleForm.insufficient': 'Insufficient materials',
    'saleForm.saving': 'Saving sale...',
    'saleForm.submit': 'Create sale',
    'purchases.title': 'Purchases',
    'purchases.description':
      'Register incoming material purchases to increase real inventory and update material valuation.',
    'purchases.register': 'Register purchase',
    'purchases.registerDescription': 'Every purchase increases material stock.',
    'purchases.history': 'Purchase history',
    'purchases.historyDescription': 'Every incoming inventory movement in one place.',
    'purchases.empty': 'No purchases recorded yet.',
    'purchases.date': 'Date',
    'purchases.material': 'Material',
    'purchases.quantity': 'Quantity',
    'purchases.cost': 'Cost',
    'purchases.total': 'Total',
    'purchaseForm.material': 'Material',
    'purchaseForm.selectMaterial': 'Select a material',
    'purchaseForm.quantity': 'Quantity',
    'purchaseForm.cost': 'Cost',
    'purchaseForm.saving': 'Saving...',
    'purchaseForm.submit': 'Register purchase',
    'inventory.title': 'Inventory',
    'inventory.description':
      'Products are virtual. This view shows how many units you can manufacture based on current material availability.',
    'inventory.overview': 'Production capacity',
    'inventory.overviewDescription': 'How many finished products can be produced with current materials.',
    'inventory.empty': 'Add products with materials to calculate production capacity.',
    'inventory.product': 'Product',
    'inventory.materialCount': 'Materials',
    'inventory.producibleUnits': 'Producible units',
    'inventory.bottleneck': 'Bottleneck material',
    'inventory.value': 'Sale value',
    'revenue.empty': 'Revenue will appear here as soon as you log sales.',
  },
  es: {
    'app.setup': 'Configuracion de AERA',
    'app.missingSupabase': 'Falta configurar Supabase',
    'app.missingSupabaseBody':
      'La app no puede iniciar porque no existe un archivo .env con las variables de entorno requeridas.',
    'app.createEnv': 'Crea un archivo `.env` en la raiz del proyecto con:',
    'app.restartVite': 'Luego reinicia Vite con `npm run dev`.',
    'layout.brandTitle': 'Operacion de perfumes con claridad',
    'layout.mobileTitle': 'Centro operativo',
    'layout.signOut': 'Cerrar sesion',
    'layout.language': 'Idioma',
    'layout.theme': 'Tema',
    'layout.openMenu': 'Abrir menu',
    'layout.closeMenu': 'Cerrar menu',
    'layout.themeLight': 'Claro',
    'layout.themeDark': 'Oscuro',
    'layout.langEnglish': 'Ingles',
    'layout.langSpanish': 'Espanol',
    'nav.dashboard': 'Panel',
    'nav.products': 'Productos',
    'nav.materials': 'Materiales',
    'nav.sales': 'Ventas',
    'nav.purchases': 'Compras',
    'nav.inventory': 'Inventario',
    'auth.welcome': 'Bienvenido',
    'auth.loginTitle': 'Inicia sesion en AERA',
    'auth.registerTitle': 'Crea tu cuenta',
    'auth.subtitle':
      'Usa la autenticacion de Supabase con correo y contrasena para acceder a tu espacio privado.',
    'auth.email': 'Correo',
    'auth.password': 'Contrasena',
    'auth.submitWait': 'Espera un momento...',
    'auth.signIn': 'Iniciar sesion',
    'auth.createAccount': 'Crear cuenta',
    'auth.needAccount': 'Necesitas una cuenta? Registrate',
    'auth.haveAccount': 'Ya tienes una cuenta? Inicia sesion',
    'auth.created': 'Cuenta creada. Revisa tu correo si la confirmacion esta habilitada.',
    'auth.failed': 'La autenticacion fallo.',
    'auth.heroTitle': 'Contabilidad e inventario para marcas modernas de perfumes.',
    'auth.heroDescription':
      'Controla productos, compras, ventas, stock y rentabilidad desde un espacio limpio.',
    'auth.cardSalesTitle': 'Control de ventas',
    'auth.cardSalesCopy': 'Ventas con multiples items y totales en vivo',
    'auth.cardPurchasesTitle': 'Flujo de compras',
    'auth.cardPurchasesCopy': 'Ingreso rapido de inventario y costos',
    'auth.cardProfitTitle': 'Visibilidad de ganancia',
    'auth.cardProfitCopy': 'KPIs y margen en un solo panel',
    'pageHeader.eyebrow': 'Resumen del negocio',
    'dashboard.title': 'Panel',
    'dashboard.description':
      'Sigue el rendimiento de tu negocio con un resumen premium de ingresos, margen e inventario.',
    'dashboard.totalSales': 'Ventas totales',
    'dashboard.grossProfit': 'Ganancia bruta',
    'dashboard.materialsValue': 'Valor de materiales',
    'dashboard.profitMargin': 'Margen de ganancia',
    'dashboard.lowStock': 'Alertas de stock',
    'dashboard.revenueTrend': 'Tendencia de ingresos',
    'dashboard.revenueTrendDescription':
      'Vista simplificada de ventas recientes con una grafica limpia y sin ejes.',
    'dashboard.loading': 'Cargando analitica...',
    'dashboard.lowStockAlerts': 'Materiales con stock bajo',
    'dashboard.lowStockDescription': 'Materiales que estan cerca de agotarse con un umbral por defecto.',
    'dashboard.lowStockEmpty': 'No hay alertas de stock bajo en este momento.',
    'dashboard.lowStockThreshold': 'Umbral',
    'materials.title': 'Materiales',
    'materials.description':
      'Gestiona tu inventario real de alcohol, esencias, frascos y cada insumo de produccion.',
    'materials.add': 'Agregar material',
    'materials.edit': 'Editar material',
    'materials.formDescription': 'Crea y actualiza materias primas usadas en produccion.',
    'materials.catalog': 'Inventario de materiales',
    'materials.catalogDescription': 'Niveles actuales de stock para cada insumo de tu operacion.',
    'materials.empty': 'Aun no hay materiales. Agrega tu primer insumo para empezar a producir.',
    'materials.name': 'Nombre',
    'materials.stock': 'Stock',
    'materials.unit': 'Unidad',
    'materials.actions': 'Acciones',
    'materials.editAction': 'Editar',
    'materials.deleteAction': 'Eliminar',
    'products.title': 'Productos',
    'products.description':
      'Mantiene tu catalogo de perfumes y define exactamente que materiales consume cada producto.',
    'products.add': 'Agregar producto',
    'products.edit': 'Editar producto',
    'products.formDescription': 'Crea productos con precio y formula de materiales.',
    'products.catalog': 'Catalogo',
    'products.catalogDescription': 'Todos los productos disponibles en tu cuenta.',
    'products.empty': 'Aun no hay productos. Agrega tu primer perfume para comenzar.',
    'products.name': 'Nombre',
    'products.price': 'Precio',
    'products.bom': 'Composicion',
    'products.bomEmpty': 'Sin materiales asignados',
    'products.actions': 'Acciones',
    'products.editAction': 'Editar',
    'products.deleteAction': 'Eliminar',
    'productForm.name': 'Nombre del producto',
    'productForm.price': 'Precio de venta',
    'productForm.placeholder': 'Eau de Parfum',
    'productForm.composition': 'Formula de materiales',
    'productForm.selectMaterial': 'Selecciona un material',
    'productForm.quantityRequired': 'Cantidad por unidad',
    'productForm.addMaterial': 'Agregar material',
    'productForm.removeMaterial': 'Quitar',
    'productForm.emptyBom': 'Agrega al menos un material para definir la composicion.',
    'productForm.save': 'Guardando...',
    'productForm.update': 'Actualizar',
    'productForm.add': 'Agregar producto',
    'productForm.cancel': 'Cancelar',
    'materialForm.name': 'Nombre del material',
    'materialForm.stock': 'Stock actual',
    'materialForm.unit': 'Unidad',
    'materialForm.placeholder': 'Alcohol',
    'materialForm.unitPlaceholder': 'ml, gramos, unidades',
    'materialForm.save': 'Guardando...',
    'materialForm.update': 'Actualizar',
    'materialForm.add': 'Agregar material',
    'materialForm.cancel': 'Cancelar',
    'sales.title': 'Ventas',
    'sales.description':
      'Registra ventas y consume automaticamente las materias primas requeridas por cada composicion.',
    'sales.newSale': 'Nueva venta',
    'sales.newSaleDescription':
      'Cada venta valida la disponibilidad de materiales antes de confirmarse.',
    'sales.history': 'Ventas recientes',
    'sales.historyDescription': 'Historial de transacciones registradas.',
    'sales.empty': 'Aun no hay ventas registradas.',
    'sales.date': 'Fecha',
    'sales.items': 'Items',
    'sales.total': 'Total',
    'sales.productFallback': 'Producto',
    'sales.validationError': 'Materiales insuficientes',
    'sales.ready': 'Materiales disponibles',
    'saleForm.product': 'Producto',
    'saleForm.selectProduct': 'Selecciona un producto',
    'saleForm.quantity': 'Cantidad',
    'saleForm.price': 'Precio',
    'saleForm.remove': 'Quitar',
    'saleForm.addLine': 'Agregar otro item',
    'saleForm.calculatedTotal': 'Total calculado',
    'saleForm.validationHint': 'AERA validara los materiales requeridos antes de guardar la venta.',
    'saleForm.insufficient': 'Materiales insuficientes',
    'saleForm.saving': 'Guardando venta...',
    'saleForm.submit': 'Crear venta',
    'purchases.title': 'Compras',
    'purchases.description':
      'Registra compras de materiales para aumentar el inventario real y actualizar la valorizacion.',
    'purchases.register': 'Registrar compra',
    'purchases.registerDescription': 'Cada compra aumenta el stock del material.',
    'purchases.history': 'Historial de compras',
    'purchases.historyDescription': 'Cada movimiento de inventario entrante en un solo lugar.',
    'purchases.empty': 'Aun no hay compras registradas.',
    'purchases.date': 'Fecha',
    'purchases.material': 'Material',
    'purchases.quantity': 'Cantidad',
    'purchases.cost': 'Costo',
    'purchases.total': 'Total',
    'purchaseForm.material': 'Material',
    'purchaseForm.selectMaterial': 'Selecciona un material',
    'purchaseForm.quantity': 'Cantidad',
    'purchaseForm.cost': 'Costo',
    'purchaseForm.saving': 'Guardando...',
    'purchaseForm.submit': 'Registrar compra',
    'inventory.title': 'Inventario',
    'inventory.description':
      'Los productos son virtuales. Esta vista muestra cuantas unidades puedes fabricar segun los materiales disponibles.',
    'inventory.overview': 'Capacidad de produccion',
    'inventory.overviewDescription': 'Cuantas unidades terminadas se pueden producir con los materiales actuales.',
    'inventory.empty': 'Agrega productos con materiales para calcular la capacidad de produccion.',
    'inventory.product': 'Producto',
    'inventory.materialCount': 'Materiales',
    'inventory.producibleUnits': 'Unidades producibles',
    'inventory.bottleneck': 'Material limitante',
    'inventory.value': 'Valor de venta',
    'revenue.empty': 'Los ingresos apareceran aqui en cuanto registres ventas.',
  },
}

function readLanguage(): Language {
  if (typeof window === 'undefined') return 'es'
  const value = window.localStorage.getItem('aera-language')
  return value === 'en' || value === 'es' ? value : 'es'
}

function readTheme(): Theme {
  if (typeof window === 'undefined') return 'light'
  const value = window.localStorage.getItem('aera-theme')
  return value === 'dark' || value === 'light' ? value : 'light'
}

export function PreferencesProvider({ children }: PropsWithChildren) {
  const [language, setLanguage] = useState<Language>(readLanguage)
  const [theme, setTheme] = useState<Theme>(readTheme)

  useEffect(() => {
    window.localStorage.setItem('aera-language', language)
    document.documentElement.lang = language
  }, [language])

  useEffect(() => {
    window.localStorage.setItem('aera-theme', theme)
    document.documentElement.classList.toggle('dark', theme === 'dark')
  }, [theme])

  const value = useMemo<PreferencesContextValue>(
    () => ({
      language,
      locale: language === 'es' ? 'es-CO' : 'en-US',
      setLanguage,
      setTheme,
      t: (key) => translations[language][key],
      theme,
    }),
    [language, theme],
  )

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>
}
